// Generated from docs/design-system/project/tokens.json. Edit the tokens, not this file.
package dev.flowpilot.app.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

internal val FlowPilotLight = lightColorScheme(
    primary = Color(0xFF216A5E),
    onPrimary = Color(0xFFE3FFF7),
    primaryContainer = Color(0xFFAAF0E0),
    onPrimaryContainer = Color(0xFF0B5C51),
    secondary = Color(0xFF4B645E),
    onSecondary = Color(0xFFE3FFF7),
    secondaryContainer = Color(0xFFCDE8E1),
    onSecondaryContainer = Color(0xFF3E5751),
    tertiary = Color(0xFF805200),
    onTertiary = Color(0xFFFFF0E2),
    tertiaryContainer = Color(0xFFFEA600),
    onTertiaryContainer = Color(0xFF4E3000),
    error = Color(0xFFA83836),
    onError = Color(0xFFFFF7F6),
    errorContainer = Color(0xFFFA746F),
    onErrorContainer = Color(0xFF6E0A12),
    surface = Color(0xFFF6FAF8),
    onSurface = Color(0xFF2A3532),
    surfaceVariant = Color(0xFFDAE5E1),
    onSurfaceVariant = Color(0xFF57615E),
    surfaceDim = Color(0xFFD1DDD8),
    surfaceBright = Color(0xFFF6FAF8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEEF5F2),
    surfaceContainer = Color(0xFFE7F0EC),
    surfaceContainerHigh = Color(0xFFE1EAE6),
    surfaceContainerHighest = Color(0xFFDAE5E1),
    outline = Color(0xFF727D7A),
    outlineVariant = Color(0xFFA9B4B1),
    inverseSurface = Color(0xFF0A0F0E),
    inverseOnSurface = Color(0xFF999E9C),
    inversePrimary = Color(0xFFB8FFEF),
    primaryFixed = Color(0xFFAAF0E0),
    primaryFixedDim = Color(0xFF9CE2D2),
    onPrimaryFixed = Color(0xFF00483E),
    onPrimaryFixedVariant = Color(0xFF1C665A),
    tertiaryFixed = Color(0xFFFEA600),
    tertiaryFixedDim = Color(0xFFEB9A00),
    onTertiaryFixed = Color(0xFF301C00),
    scrim = Color(0xFF000000),
    background = Color(0xFFF6FAF8),
    onBackground = Color(0xFF2A3532),
    surfaceTint = Color(0xFF216A5E),
)

internal val FlowPilotDark = darkColorScheme(
    primary = Color(0xFF9DD1C5),
    onPrimary = Color(0xFF12483F),
    primaryContainer = Color(0xFF285B51),
    onPrimaryContainer = Color(0xFFB9EEE1),
    secondary = Color(0xFFB1CCC5),
    onSecondary = Color(0xFF2C453F),
    secondaryContainer = Color(0xFF27403B),
    onSecondaryContainer = Color(0xFFAAC5BE),
    tertiary = Color(0xFFFFB959),
    onTertiary = Color(0xFF5B3900),
    tertiaryContainer = Color(0xFFFEA600),
    onTertiaryContainer = Color(0xFF4E3000),
    error = Color(0xFFFA746F),
    onError = Color(0xFF490006),
    errorContainer = Color(0xFF871F21),
    onErrorContainer = Color(0xFFFF9993),
    surface = Color(0xFF0A0F0E),
    onSurface = Color(0xFFDDE8E4),
    surfaceVariant = Color(0xFF1E2825),
    onSurfaceVariant = Color(0xFFA2ADAA),
    surfaceDim = Color(0xFF0A0F0E),
    surfaceBright = Color(0xFF242E2C),
    surfaceContainerLowest = Color(0xFF000000),
    surfaceContainerLow = Color(0xFF0E1513),
    surfaceContainer = Color(0xFF131B19),
    surfaceContainerHigh = Color(0xFF19211F),
    surfaceContainerHighest = Color(0xFF1E2825),
    outline = Color(0xFF6D7874),
    outlineVariant = Color(0xFF404A47),
    inverseSurface = Color(0xFFF6FAF8),
    inverseOnSurface = Color(0xFF515654),
    inversePrimary = Color(0xFF35685E),
    primaryFixed = Color(0xFFB8EDE1),
    primaryFixedDim = Color(0xFFAADFD3),
    onPrimaryFixed = Color(0xFF10473E),
    onPrimaryFixedVariant = Color(0xFF32645A),
    tertiaryFixed = Color(0xFFFEA600),
    tertiaryFixedDim = Color(0xFFEB9A00),
    onTertiaryFixed = Color(0xFF301C00),
    scrim = Color(0xFF000000),
    background = Color(0xFF0A0F0E),
    onBackground = Color(0xFFDDE8E4),
    surfaceTint = Color(0xFF9DD1C5),
)

@Immutable
data class FlowPilotColors(
    val diffAddBg: Color,
    val diffAddInk: Color,
    val diffRemoveBg: Color,
    val diffRemoveInk: Color,
    val codeBg: Color,
    val codeInk: Color,
    val codeKeyword: Color,
    val codeString: Color,
    val codeNumber: Color,
    val codeComment: Color,
    val codeFunction: Color,
    val terminalPrompt: Color,
)

internal val CodeColorsLight = FlowPilotColors(
    diffAddBg = Color(0xFFD4F3E8),
    diffAddInk = Color(0xFF0B5C4F),
    diffRemoveBg = Color(0xFFFFE2DE),
    diffRemoveInk = Color(0xFF9A2A2A),
    codeBg = Color(0xFFF0F5F3),
    codeInk = Color(0xFF1F2A27),
    codeKeyword = Color(0xFF7A3FB0),
    codeString = Color(0xFF1D6B3A),
    codeNumber = Color(0xFF9B4A00),
    codeComment = Color(0xFF5D6966),
    codeFunction = Color(0xFF155F8A),
    terminalPrompt = Color(0xFF216A5E),
)

internal val CodeColorsDark = FlowPilotColors(
    diffAddBg = Color(0xFF123A31),
    diffAddInk = Color(0xFF9EE6D2),
    diffRemoveBg = Color(0xFF43191A),
    diffRemoveInk = Color(0xFFFFB1AB),
    codeBg = Color(0xFF0C1311),
    codeInk = Color(0xFFD9E5E1),
    codeKeyword = Color(0xFFD6B4FF),
    codeString = Color(0xFF9FE0B1),
    codeNumber = Color(0xFFFFC08A),
    codeComment = Color(0xFF8B9894),
    codeFunction = Color(0xFF9CCFFF),
    terminalPrompt = Color(0xFF7FDCC5),
)
